name: Changelog Update

on:
  push:
    branches: [ dev ]

# Want to read in the pull_request_template submitted file, grab the version update degree and comments,
# Grab the current Changelog file version, and append new information to the changelog
jobs:
  release:
    name: Build Docker image and push to DockerHub
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Dockerhub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Get release version
        run: |
          export COMPAS_VERSION=$(sed -n '/const std::string VERSION_STRING/,/^$/p' ./src/constants.h | sed 's/.*"\(.*\)"[^"]*$/\1/')
          echo "::set-env name=COMPAS_VERSION::$COMPAS_VERSION"
        
      - name: Print version
        run: echo $COMPAS_VERSION
        
      - name: Build and tag Docker image
        run: docker build -t teamcompas/compas:$COMPAS_VERSION -t teamcompas/compas:latest .
        
      - name: Push Docker image
        run: |
          docker push teamcompas/compas:$COMPAS_VERSION
          docker push teamcompas/compas:latest
          
